// Steven Fang something along the lines for the mongo database should go like this
// this is untested since i can't get in touch with steven stapleton

$(document).ready(function(){
    //button when clicked to check if password matches username
    $("#checkDatabase").click(sendPassword);
    $("#signupButton").click(signup);
});

function sendPassword(){
  // this gets the username
  var username = ("#userName").val(data.name.split("_").join(" "));

  console.log("Requesting userName");

  $.ajax({method:"GET",
        url: "/Password/"+name,
        dataType:"json",
        success: function(data){
          console.log("Loading recipe into form: ",data);
          // the password generated by the user
          var password = data.password;
          // this gets the password thats already on the website
          //basically the user inputted password
          var input = document.getElementById('password').value;
          if(password == input){
            //do something when it works
          }else{
            //do something when it doesn't work maybe try again?
          }
        },
        cache:false
  });
}

// post password/user onto the DATABASE
function signup(){
  console.log("Sending password scheme");

  //get the username
  var username = {
    name: $("#userName").val().split(" ").join("_")
  }
  $.ajax({method:"POST",
				url:"/password",
				data:recipe,
				success:function(data){
          //do something when it works, maybe a message?
				}
	});

}
